services:
  db:
    image: postgres:18-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
