services:
  app:
    build: 
      context: .
      target: dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT:-5173}:5173
    depends_on:
      - db
  db:
    image: postgres:18-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  adminer:
    image: adminer:5
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  pgdata: